---
- name: lcm-version-file
  copy:
    content: "{{ vars[item + '_version'] }}"
    dest: "{{ vars[item + '_lcm']['version-file'] }}"
    mode: 0644
  with_items: '{{ lcm_roles_node }}'
  when: lcm_write_version_file
