---
- block:
  - name: Stat secret dir
    stat:
      path: "{{ item }}"
    with_items: "{{ common_secrets_dirs }}"
    register: _secrets_dirs
    delegate_to: localhost  # control node

  - name: Include secrets
    include_vars:
      dir: "{{ item['item'] }}"
    with_items: "{{ _secrets_dirs['results'] }}"
    loop_control:
      label: "{{ item['item'] }}"
    when: item.stat.exists
    no_log: "{{ common_secrets_no_log|default(False) }}"
  when: common_secrets_dirs|default(False)
