---
- name: Update Repository cache
  apt:
    update_cache: true
    force_apt_get: true

- name: Add PostgreSQL APT key
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: PostgreSQL APT repository
  ansible.builtin.apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_lsb.codename }}-pgdg main"
    filename: pgdg.list

- name: Install PostgreSQL client
  package:
    name: "{{ postgresql_client_versions[postgresql_client_version]['package'] }}={{ postgresql_client_versions[postgresql_client_version]['version'] }}"
    state: present
