
namespace: c2platform
name: core

version: 1.0.0

authors:
- Onno van der Straaten (https://github.com/onknows)

description: C2 Platform Ansible Collection with Core Roles, Modules, Filters
license_file: LICENSE
readme: README.md

tags: []

dependencies: {}

repository: https://github.com/c2platform/ansible-collection-core
documentation: https://github.com/c2platform/ansible-collection-core
homepage: https://github.com/c2platform/
issues: https://github.com/c2platform/ansible-collection-core/issues

build_ignore: []
