---
- name: Ansible roles names without prefix
  set_fact:
    ansible_role_names_cleaned: "{{ ansible_role_names|
                 map('regex_replace', regex, replace)|
                 list }}"
  vars:
    regex: '^(.*)\.(.*)$'
    replace: '\2'

- name: lcm_roles_node
  set_fact: lcm_roles_node="{{ lcm_roles | intersect(ansible_role_names_cleaned) }}"

- name: Determine LCM info facts
  c2platform.core.lcm_info:
    role: '{{ item }}'
    version: "{{ vars[item + '_version'] }}"
    version_prepare: "{{ vars[item + '_version_prepare']|default(omit) }}"
    home: "{{ vars[item + '_home'] }}"
    database: "{{ vars[item + '_database_name']|default(omit) }}"
    versions_sequence: "{{ vars[item + '_versions_sequence'] }}"
  with_items: '{{ lcm_roles_node }}'

- name: LCM info facts
  debug:
    msg:
      - "{{ item }}_lcm['operation']: {{ vars[item + '_lcm']['operation']|default('not defined') }}"
      - "{{ item }}_lcm_operation: {{ vars[item + '_lcm_operation']|default('not defined') }}"
      - "{{ item }}_lcm['version-file']: {{ vars[item + '_lcm']['version-file']|default('not defined') }}"
      - "{{ item }}_lcm['operation-description']: {{ vars[item + '_lcm']['operation-description']|default('not defined') }}"
      - "{{ item }}_version: {{ vars[item + '_version']|default('not defined') }}"
      - "{{ item }}_home: {{ vars[item + '_home']|default('not defined') }}"
      - "{{ item }}_database_name_version: {{ vars[item + '_database_name_version']|default('not defined') }}"
      - "{{ item }}_database_name_version_backup: {{ vars[item + '_database_name_version_backup']|default('not defined') }}"
      - "{{ item }}_database_template: {{ vars[item + '_database_template']|default('not defined') }}"
      - "{{ item }}_home_version: {{ vars[item + '_home_version']|default('not defined') }}"
      - "{{ item }}_home_version_current: {{ vars[item + '_home_version_current']|default('not defined') }}"
      - "{{ item }}_home_version_home: {{ vars[item + '_home_version_home']|default('not defined') }}"
      - "{{ item }}_home_version_home_current: {{ vars[item + '_home_version_home_current']|default('not defined') }}"
      - "{{ item }}_home_version_app: {{ vars[item + '_home_version_app']|default('not defined') }}"
      - "{{ item }}_home_version_app_current: {{ vars[item + '_home_version_app_current']|default('not defined') }}"
      - "{{ item }}_home_link: {{ vars[item + '_home_link']|default('not defined') }}"
      - "{{ item }}_home_link_home: {{ vars[item + '_home_link_home']|default('not defined') }}"
      - "{{ item }}_home_link_app: {{ vars[item + '_home_link_app']|default('not defined') }}"
      - "{{ item }}_home_link_app: {{ vars[item + '_home_link_app']|default('not defined') }}"
      - "{{ item }}_home_backup: {{ vars[item + '_home_backup']|default('not defined') }}"
      - "{{ item }}_home_backup_version: {{ vars[item + '_home_backup_version']|default('not defined') }}"
      - "{{ item }}_home_version_prepare: {{ vars[item + '_home_version_prepare']|default('not defined') }}"
      - "{{ item }}_home_version_home_prepare: {{ vars[item + '_home_version_home_prepare']|default('not defined') }}"
  with_items: '{{ lcm_roles_node }}'
