---
- name: Set fact node roles
  set_fact: alias_roles_node="{{ alias_roles | intersect(ansible_role_names_cleaned) }}"

- name: Alias file
  template:
    src: c2.sh.j2
    dest: "/etc/profile.d/alias-{{ item }}.sh"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ alias_roles_node }}"
