---
- name: Authenticate
  uri:
    url: https://bkd-am.bkd.local:8443/acs/json/realms/root/authenticate
    method: POST
    headers:
      X-OpenAM-Username: amadmin
      X-OpenAM-Password: supersecret
      Content-Type: application/json
      Accept-API-Version: resource=2.0, protocol=1.0
    timeout: 10
    validate_certs: no
  register: _authenticate_am

- set_fact:
    am_token: "{{ _authenticate_am['json']['tokenId'] }}"

- name: Create user # list bestaat niet
  uri:
    url: https://bkd-am.bkd.local:8443/acs/json/realms/root/users/?_action=create
    method: POST
    headers:
      samb: "{{ am_token }}"
      Content-Type: application/json
      Accept-API-Version: resource=3.0, protocol=2.1
    body_format: json
    body:
      username: amUserAdmin
      userpassword: supersecret
    status_code: [201,409] # 409 is conflicet / resource exists
    timeout: 10
    validate_certs: no
  register: _create_user
  changed_when: _create_user['status'] == 201

- name: Create admin group
  uri:
    url: https://bkd-am.bkd.local:8443/acs/json/realms/root/groups?_action=create
    method: POST
    headers:
      samb: "{{ am_token }}"
      Content-Type: application/json
      Accept-API-Version: resource=3.0, protocol=2.1
    body_format: json
    body:
      username: amDelegates
    status_code: [201,409] # 409 is conflicet / resource exists
    timeout: 10
    validate_certs: no
  register: _create_admin_group
  changed_when: _create_admin_group['status'] == 201

- copy: # debug
    content: "{{ {'_create_admin_group': _create_admin_group }|to_nice_yaml }}"
    dest: /vagrant/_create_admin_group.yml

- name: Add admin user to group
  uri:
    url: https://bkd-am.bkd.local:8443/acs/json/realms/root/groups/amDelegates
    method: PUT
    headers:
      samb: "{{ am_token }}"
      Content-Type: application/json
      Accept-API-Version: resource=3.0, protocol=2.1
    body_format: json
    body:
      uniquemember:
        - uid=amUserAdmin,ou=people,dc=bkwi,dc=nl
    status_code: [200]
    timeout: 10
    validate_certs: no
  register: _add_to_group
  changed_when: _create_user['status'] == 201 # workaround status this request is always 200

- name: Get privileges of group
  uri:
    url: https://bkd-am.bkd.local:8443/acs/json/realms/root/groups/amDelegates
    method: GET
    headers:
      samb: "{{ am_token }}"
      Content-Type: application/json
      Accept-API-Version: resource=3.0, protocol=2.1
    status_code: [200]
    timeout: 10
    validate_certs: no
  register: _get_group
  #changed_when: _create_user['status'] == 201 # workaround status this request is always 200

- copy: # debug
    content: "{{ {'_get_group': _get_group }|to_nice_yaml }}"
    dest: /vagrant/_get_group.yml

- name: Change privileges of group
  uri:
    url: https://bkd-am.bkd.local:8443/acs/json/realms/root/groups/amDelegates
    method: PUT
    headers:
      samb: "{{ am_token }}"
      Content-Type: application/json
      Accept-API-Version: resource=4.0, protocol=2.0
    body_format: json
    body:
      _id: amDelegates
      username: amDelegates
      realm: "/"
      universalid:
      - id=amDelegates,ou=group,ou=am-config
      members:
        uniqueMember:
        - amUserAdmin
      cn:
      - amDelegates
      privileges:
        RealmAdmin: true
        LogAdmin: false
        LogRead: false
        LogWrite: true
        AgentAdmin: false
        FederationAdmin: false
        RealmReadAccess: false
        PolicyAdmin: true
        EntitlementRestAccess: false
        PrivilegeRestReadAccess: true
        PrivilegeRestAccess: true
        ApplicationReadAccess: false
        ApplicationModifyAccess: false
        ResourceTypeReadAccess: false
        ResourceTypeModifyAccess: false
        ApplicationTypesReadAccess: false
        ConditionTypesReadAccess: false
        SubjectTypesReadAccess: false
        DecisionCombinersReadAccess: false
        SubjectAttributesReadAccess: false
        SessionPropertyModifyAccess: false
    status_code: [200]
    timeout: 10
    validate_certs: no
  register: _add_to_group
  # changed_when: _create_user['status'] == 201 # workaround status this request is always 200

- copy: # debug
    content: "{{ {'_add_to_group': _add_to_group }|to_nice_yaml }}"
    dest: /vagrant/_add_to_group.yml
