---
- name: Bundle facts
  set_fact:
    jdk: "{{ java_versions[bundle_java_version] }}"

- name: Download bundle
  get_url:
    url: "{{ item['url'] }}"
    checksum: "{{ item['checksum']|default(omit) }}"
    dest: "/var/tmp/bundle-cert-{{ bundle_java_version }}-{{ item['url']|checksum }}"
    validate_certs: no
  with_items: "{{ java_versions[bundle_java_version]['bundles'] }}"
  register: bundles_download

- block:
  - name: "Remove bundles"
    java_cert:
      cert_alias: "{{ item['alias'] }}"
      cert_path: "/var/tmp/bundle-cert-{{ bundle_java_version }}-{{ item['url']|checksum }}"
      keystore_path: "{{ jdk['keystore'] }}"
      keystore_pass: "{{ jdk['keystore_pass']|default('changeit') }}"
      executable: "{{ jdk['keytool'] }}"
      state: absent
    with_items: "{{ java_versions[bundle_java_version]['bundles'] }}"
    ignore_errors: yes
    notify: "{{ jdk['notify']|default(omit) }}"

  - name: "Import bundles"
    java_cert:
      cert_alias: "{{ item['alias'] }}"
      cert_path: "/var/tmp/bundle-cert-{{ bundle_java_version }}-{{ item['url']|checksum }}"
      keystore_path: "{{ jdk['keystore'] }}"
      keystore_pass: "{{ jdk['keystore_pass']|default('changeit') }}"
      executable: "{{ jdk['keytool'] }}"
      state: present
    with_items: "{{ java_versions[bundle_java_version]['bundles'] }}"
    notify: "{{ jdk['notify']|default(omit) }}"
  when: bundles_download.changed
