---
- name: Bundle fact
  set_fact:
    bundles: "{{ adoptopenjdk['versions'][java_version]['bundles'] }}"
    jdk: "{{ adoptopenjdk['versions'][java_version] }}"

- debug:
    msg: "bundles: {{ bundles }}"

- debug:
    msg: "jdk: {{ jdk }}"

- name: Download bundle
  get_url:
    url: "{{ item['url'] }}"
    checksum: "{{ item['checksum']|default(omit) }}"
    dest: "/var/tmp/{{ item['url']|basename }}-{{ java_version|c2platform.core.java_folder }}"
    validate_certs: no
  with_items: "{{ bundles }}"
  register: bundles_download

- block:
    - name: "Remove bundles"
      java_cert:
        cert_alias: "{{ item['alias'] }}"
        cert_path: "/var/tmp/{{ item['url']|basename }}-{{ java_version|c2platform.core.java_folder }}"
        keystore_path: "{{ java_version|c2platform.core.java_keystore(jdk) }}"
        keystore_pass: "{{ jdk['keystore_pass']|default('changeit') }}"
        executable: "{{ java_version|c2platform.core.java_keytool(jdk) }}"
        state: absent
      with_items: "{{ bundles }}"
      ignore_errors: yes
      notify: "{{ jdk['notify']|default(omit) }}"

    - name: "Add bundles"
      java_cert:
        cert_alias: "{{ item['alias'] }}"
        cert_path: "/var/tmp/{{ item['url']|basename }}-{{ java_version|c2platform.core.java_folder }}"
        keystore_path: "{{ java_version|c2platform.core.java_keystore(jdk) }}"
        keystore_pass: "{{ jdk['keystore_pass']|default('changeit') }}"
        executable: "{{ java_version|c2platform.core.java_keytool(jdk) }}"
        state: present
      with_items: "{{ bundles }}"
      ignore_errors: yes
      notify: "{{ jdk['notify']|default(omit) }}"
  when: bundles_download.changed
