---
- name: Check installed
  stat:
    path: "{{ java_version|c2platform.core.java_home }}/bin/java"
  register: jdk_installed

- block:
    - name: Download
      get_url:
        url: "{{ adoptopenjdk['versions'][java_version].url }}"
        dest: "/tmp/{{ java_version|c2platform.core.java_folder }}"
        checksum: "sha256:{{ adoptopenjdk['versions'][java_version].checksum }}"

    - name: Create java_home
      file:
        path: "{{ java_version|c2platform.core.java_home }}"
        state: directory
        mode: 0755

    - name: Unarchive
      unarchive:
        src: "/tmp/{{ java_version|c2platform.core.java_folder }}"
        dest: "{{ java_version|c2platform.core.java_home }}"
        extra_opts: '--strip-components=1'
        remote_src: yes
  when: not jdk_installed.stat.exists
