---
- name: Set additional java facts
  java_facts:
    version: "{{ java_version }}"
    versions: "{{ java_versions }}"
    alternatives: "{{ java_version_alternatives }}"

- name: Install Java
  include: install.yml
  with_items: "{{ java_install_archives }}"
  loop_control:
    loop_var: jiav

- name: Install Java ( package )
  package:
    name:  "{{ java_versions[item]['name']|default(item) }}"
  with_items: "{{ java_install_packages }}"

- name: Create etc profile
  copy:
    content: |
      export JAVA_HOME={{ java_versions[java_version]['java_home'] }}
      export PATH=$JAVA_HOME/bin:$PATH
    dest: /etc/profile.d/java.sh
    mode: 0644
  when: java_home_etc_profile|default(False)

- name: Import bundles
  include: bundles.yml
  with_items: "{{ java_install_archives + java_install_packages }}"
  loop_control:
    loop_var: bundle_java_version
  when: java_versions[java_version]['bundles'] is defined

- name: Import trusted sites
  include: sites.yml
  with_items: "{{ java_versions }}"
  loop_control:
    loop_var: java_version_site
  when: java_trusted_sites is defined and java_trusted_sites_enabled|default(False)
