---
- include: install.yml
  when: adoptopenjdk.version|default(False)

- include: bundles.yml
  when: adoptopenjdk.version|default(False) and adoptopenjdk['versions'][adoptopenjdk['version']]['bundles'] is defined
