---
- name: Set additional java facts
  java_facts:
    version: "{{ java_version }}"
    versions: "{{ java_versions }}"
    alternatives: "{{ java_version_alternatives }}"
    java_trusts: "{{ java_trusts }}"

- name: Install Java
  include: install.yml
  with_items: "{{ java_install_archives }}"
  loop_control:
    loop_var: jiav
  when: java_versions[jiav]['install']|default(True)

- name: Install Java ( package )
  package:
    name:  "{{ java_versions[item]['name']|default(item) }}"
  with_items: "{{ java_install_packages }}"
  when: java_versions[item]['install']|default(True)

- name: Create etc profile
  copy:
    content: |
      export JAVA_HOME={{ java_versions[java_version]['java_home'] }}
      export PATH=$JAVA_HOME/bin:$PATH
    dest: /etc/profile.d/java.sh
    mode: 0644
  when: java_home_etc_profile|default(False)

- name: Configure trusts
  include: trusts.yml
  with_items: "{{ java_install_archives + java_install_packages }}"
  loop_control:
    loop_var: java_version_with_trusts
  when: java_versions[java_version_with_trusts]['trusts'] is defined or java_trusts|length > 0
