---
- name: Java install fact
  set_fact:
    java_versions: "{{ [java['version']] + java['version_alternatives'] }}"

- name: Install Java
  include: install.yml
  with_items: "{{ java_versions }}"
  loop_control:
    loop_var: java_version

- name: JDK in etc profile
  copy:
    content: "export JAVA_HOME={{ java['version']|c2platform.core.java_home }}"
    dest: /etc/profile.d/jdk.sh
    mode: 0644

- name: Import bundles
  include: bundles.yml
  with_items: "{{ java_versions }}"
  loop_control:
    loop_var: java_version
  when: java['versions'][java_version]['bundles'] is defined

- name: Import trusted sites
  include: sites.yml
  with_items: "{{ java_versions }}"
  loop_control:
    loop_var: java_version
  when: java_trusted_sites is defined and java_trusted_sites_enabled|default(False)
