---
- include: packages.yml
- include: pip.yml
- include: mounts.yml
- include: user.yml
  when: common_ansible_user_create

- name: etc environment
  template:
    src: etc_environment.j2
    dest: /etc/environment
    mode: 0644
  when: common_manage_etc_environment|default(False)

- name: Custom prompt
  copy:
    content: 'export PS1="{{ common_terminal_prompt }}"'
    dest: /etc/profile.d/custom_prompt.sh
    mode: 0644
  when: common_terminal_prompt is defined

- name: Remove custom prompt
  file:
    state: absent
    path: /etc/profile.d/custom_prompt.sh
  when: common_terminal_prompt is not defined

- name: Include secrets
  include_vars:
    dir: "{{ common_secrets_dir }}"
  when: common_secrets_dir|default(False)
  no_log: false # TODO
