---
- name: NFS mounts
  mount:
    path: "{{ item['path'] }}"
    src: "{{ item['src'] }}"
    fstype: "{{ item['fstype'] }}"
    opts: "{{ item['opts'] }}"
    state: "{{ item['state'] }}"
  with_items: '{{ nfs_mounts }}'
  ignore_errors: True