---
- name: Allow sessions
  postgresql_query:
    db: postgres
    port: "{{ vars[ lcm_role_upgrade + '_database_port' ] }}"
    query: update pg_database SET datallowconn = 'true' WHERE datname = %s
    positional_args:
      - "{{ allow_database }}"
