---
- name: Allow sessions
  postgresql_query:
    db: postgres
    query: update pg_database SET datallowconn = 'true' WHERE datname = %s
    positional_args:
      - "{{ allow_database }}"
  vars:
    ansible_ssh_pipelining: true
