---
- name: Block sessions
  postgresql_query:
    db: postgres
    port: "{{ vars[ lcm_role_upgrade + '_database_port' ] }}"
    query: update pg_database SET datallowconn = 'false' WHERE datname = %s
    positional_args:
      - "{{ terminate_database }}"

- name: Terminate sessions
  postgresql_query:
    db: postgres
    port: "{{ vars[ lcm_role_upgrade + '_database_port' ] }}"
    query: select pg_terminate_backend(pid) from pg_stat_activity where datname = %s
    positional_args:
      - "{{ terminate_database }}"
