---
- name: Block sessions
  postgresql_query:
    db: postgres
    query: update pg_database SET datallowconn = 'false' WHERE datname = %s
    positional_args:
      - "{{ terminate_database }}"
  vars:
    ansible_ssh_pipelining: true

- name: Terminate sessions
  postgresql_query:
    db: postgres
    query: select pg_terminate_backend(pid) from pg_stat_activity where datname = %s
    positional_args:
      - "{{ terminate_database }}"
  vars:
    ansible_ssh_pipelining: true
