---
- name: Check JDK keystore
  stat:
    path: "{{ jdk_version_no|c2platform.core.java_keystore(jdk) }}"
  register: keystore

- block:
    - name: "Import bundles in JDK cacerts"
      java_cert:
        cert_alias: "{{ jdk['name'] }}"
        cert_path: "/tmp/{{ jdk['url']|basename }}"
        keystore_path: "{{ jdk_version_no|c2platform.core.java_keystore(jdk) }}"
        keystore_pass: "{{ jdk['keystore_pass']|default('changeit') }}"
        executable: "{{ jdk_version_no|c2platform.core.java_keytool(jdk) }}"
        state: present
      with_items: "{{ cacerts_import_certs_urls }}"
      ignore_errors: yes
      notify: "{{ jdk['notify']|default(omit) }}"

    - name: "Import trusted sites in JDK cacerts"
      java_cert:
        cert_alias: "{{ item['name'] }}"
        cert_url: "{{ item['url'] }}"
        cert_port: "{{ item['port'] }}"
        keystore_path: "{{ jdk_version_no|c2platform.core.java_keystore(jdk) }}"
        keystore_pass: "{{ jdk['keystore_pass']|default('changeit') }}"
        executable: "{{ jdk_version_no|c2platform.core.java_keytool(jdk) }}"
        state: present
      with_items: "{{ cacerts_trusted_sites }}"
      notify: "{{ item['notify']|default(omit) }}"
      register: jdk_trusted_sites # cmd, msg, rc
      ignore_errors: yes
      environment: "{{ cacerts_java_cert_environment|default(omit) }}"
  when: keystore.stat.exists
