---
- name: Create ACL
  acl:
    path: "{{ item['path'] }}"
    entity: "{{ item['entity'] }}"
    etype: "{{ item['etype'] }}"
    permissions: "{{ item['permission'] }}"
    default: "{{ item['default']|default(omit) }}"
    recursive: "{{ item['recursive']|default(omit) }}"
    state: "{{ item['state']|default(omit) }}"
  with_items: "{{ common_acl_set }}"
