---
- name: Create directory
  file:
    path: "{{ item['path'] }}"
    state: "{{ item['state']|default('directory') }}"
    owner: "{{ item['owner']|default(common_files_owner) }}"
    group: "{{ item['group']|default(common_files_group) }}"
    recurse: "{{ item['recurse']|default(omit) }}"
    src: "{{ item['src']|default(omit) }}"
    attributes: "{{ item['attributes']|default(omit) }}"
    mode: "{{ item['mode']|default('0755') }}"
  with_items: "{{ common_directories_set }}"
  loop_control:
    label: "{{ item['path'] }}"
