---
- name: Stat no update files
  stat:
    path: "{{ item['dest'] }}"
  with_items: "{{ common_files_set|selectattr('update', 'defined')|selectattr('update', 'equalto', False)|list }}"
  loop_control:
    label: "{{ item['dest'] }}"
  register: no_update_files

- name: Content file
  copy:
    content: "{{ item['content'] }}"
    dest: "{{ item['dest'] }}"
    mode: "{{ item['mode']|default('0755') }}"
    owner: "{{ item['owner']|default(omit) }}"
    group: "{{ item['group']|default(omit) }}"
  with_items: "{{ common_files_set|selectattr('content', 'defined')|list }}"
  loop_control:
    label: "{{ item['dest'] }}"
  when: not item|c2platform.core.file_exists_and_update_false(no_update_files)
  notify: "{{ item['notify']|default(omit) }}"

- include_tasks: files_src.yml

- name: Xpath file
  xml:
    path: "{{ item['dest'] }}"
    xpath: "{{ item['xpath'] }}"
    input_type: xml
    set_children: "{{ item['set_children']|default(omit) }}"
    add_children: "{{ item['add_children']|default(omit) }}"
  with_items: "{{ common_files_set|selectattr('xpath', 'defined')|list }}"
  loop_control:
    label: "{{ item['dest'] }}"
  when: not item|c2platform.core.file_exists_and_update_false(no_update_files)
  notify: "{{ item['notify']|default(omit) }}"

- name: Regex file
  replace:
    path: "{{ item['dest'] }}"
    regexp: "{{ item['regex'] }}"
    replace: "{{ item['replace'] }}"
  with_items: "{{ common_files_set|selectattr('regex', 'defined')|list }}"
  loop_control:
    label: "{{ item['dest'] }}"
  when: not item|c2platform.core.file_exists_and_update_false(no_update_files)
  # notify: "{{ item['notify']|default(omit) }}" # TODO regex will always be "changed"

- include_tasks: files_cat.yml
  with_items: "{{ common_files_set|selectattr('cat', 'defined')|list }}"
  loop_control:
    label: "{{ file_cat['dest'] }}"
    loop_var: file_cat
  when: not file_cat|c2platform.core.file_exists_and_update_false(no_update_files)

- name: Absent file
  file:
    path: "{{ item['dest'] }}"
    state: absent
  with_items: "{{ common_files_set|selectattr('state', 'defined')|selectattr('state', 'eq', 'absent')|list }}"
  loop_control:
    label: "{{ item['dest'] }}"
  notify: "{{ item['notify']|default(omit) }}"

- name: Link
  file:
    src: "{{ item['path'] }}"
    path: "{{ item['link'] }}"
    state: link
    force: "{{ item['force']|default(omit) }}"
  with_items: "{{ common_files_set|selectattr('link', 'defined')|list }}"
  loop_control:
    label: "{{ item['path'] }}"
  notify: "{{ item['notify']|default(omit) }}"
