---
- name: Set files facts
  set_fact:
    common_directories: "{{ lookup('vars', common_files_role_name + '_directories', default=[]) }}"
    common_files: "{{ lookup('vars', common_files_role_name + '_files', default=[]) }}"
    common_acl: "{{ lookup('vars', common_files_role_name + '_acl', default=[]) }}"
    common_unarchive: "{{ lookup('vars', common_files_role_name + '_unarchive', default=[]) }}"
    common_files_owner: "{{ lookup('vars', common_files_role_name + '_owner', default='root') }}"
    common_files_group: "{{ lookup('vars', common_files_role_name + '_group', default='root') }}"
    common_disabled: "{{ lookup('vars', common_files_role_name + '_disabled', default=[]) }}"
  when: common_files_role_name is defined

- include_tasks: directories.yml
  with_items: "{{ common_directories }}"
  when: common_directories is defined and common_directories_set_item not in common_disabled
  loop_control:
    loop_var: common_directories_set_item
  vars:
    common_directories_set: "{{ common_directories[common_directories_set_item] }}"

- include_tasks: files.yml
  with_items: "{{ common_files }}"
  when: common_files is defined and common_files_set_item not in common_disabled
  loop_control:
    loop_var: common_files_set_item
  vars:
    common_files_set: "{{ common_files[common_files_set_item] }}"

- include_tasks: acl.yml
  with_items: "{{ common_acl }}"
  when: common_acl is defined and common_acl_set_item not in common_disabled
  loop_control:
    loop_var: common_acl_set_item
  vars:
    common_acl_set: "{{ common_acl[common_acl_set_item] }}"

- include_tasks: unarchive.yml
  with_items: "{{ common_unarchive }}"
  when: common_unarchive is defined and common_unarchive_set_item not in common_disabled
  loop_control:
    loop_var: common_unarchive_set_item
  vars:
    common_unarchive_set: "{{ common_unarchive[common_unarchive_set_item] }}"
