---
- name: Set files facts
  set_fact:
    common_directories: "{{ hostvars[inventory_hostname][common_files_role_name+'_directories']|default([]) }}"
    common_files: "{{ hostvars[inventory_hostname][common_files_role_name+'_files']|default([]) }}"
    common_acl: "{{ hostvars[inventory_hostname][common_files_role_name+'_acl']|default([]) }}"
    common_unarchive: "{{ hostvars[inventory_hostname][common_files_role_name+'_unarchive']|default([]) }}"
    common_files_owner: "{{ hostvars[inventory_hostname][common_files_role_name+'_owner']|default('root') }}"
    common_files_group: "{{ hostvars[inventory_hostname][common_files_role_name+'_group']|default('root') }}"
  when: common_files_role_name is defined

- include_tasks: directories.yml
  with_items: "{{ common_directories }}"
  when: common_directories is defined
  loop_control:
    loop_var: common_directories_set_item
  vars:
    common_directories_set: "{{ common_directories[common_directories_set_item] }}"

- include_tasks: files.yml
  with_items: "{{ common_files }}"
  when: common_files is defined
  loop_control:
    loop_var: common_files_set_item
  vars:
    common_files_set: "{{ common_files[common_files_set_item] }}"

- include_tasks: acl.yml
  with_items: "{{ common_acl }}"
  when: common_acl is defined
  loop_control:
    loop_var: common_acl_set_item
  vars:
    common_acl_set: "{{ common_acl[common_acl_set_item] }}"

- include_tasks: unarchive.yml
  with_items: "{{ common_unarchive }}"
  when: common_unarchive is defined
  loop_control:
    loop_var: common_unarchive_set_item
  vars:
    common_unarchive_set: "{{ common_unarchive[common_unarchive_set_item] }}"
