---
#- debug:
#    msg: |
#     common_files: {{ common_files }}
#     role_name: {{ role_name }}

- include_tasks: directories.yml
  with_items: "{{ common_directories }}"
  loop_control:
    loop_var: common_directories_set_item
  vars:
    common_directories_set: "{{ common_directories[common_directories_set_item] }}"

- include_tasks: files.yml
  with_items: "{{ common_files }}"
  loop_control:
    loop_var: common_files_set_item
  vars:
    common_files_set: "{{ common_files[common_files_set_item] }}"

- include_tasks: acl.yml
  with_items: "{{ common_acl }}"
  loop_control:
    loop_var: common_acl_set_item
  vars:
    common_acl_set: "{{ common_acl[common_acl_set_item] }}"
